apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: towers.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: Tower
    listKind: TowerList
    plural: towers
    singular: tower
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
