apiVersion: tower.ansible.com/v1alpha1
kind: Tower
metadata:
  name: example-tower
  namespace: example-tower
spec:
  tower_hostname: example-tower.test
  tower_secret_key: aabbcc

  tower_admin_user: test
  tower_admin_email: test@example.com
  tower_admin_password: changeme

  tower_task_image: registry.access.redhat.com/ansible-tower-36/ansible-tower:3.6.0
  tower_web_image: registry.access.redhat.com/ansible-tower-36/ansible-tower:3.6.0

  tower_memcached_image: memcached:alpine

  tower_rabbitmq_image: rabbitmq:3

  tower_postgres_pass: awxpass
  tower_postgres_image: postgres:9.6
  tower_postgres_storage_request: 8Gi
