galaxy_info:
  author: Jeff Geerling
  description: Tower role for Tower Operator for Kubernetes.
  company: Midwestern Mac, LLC

  license: MIT

  min_ansible_version: 2.8

  galaxy_tags:
    - tower
    - awx
    - ansible
    - automation
    - ci
    - cd
    - deployment

dependencies: []
