---
- name: Verify cluster resources
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - name: Get tower Pod data
      k8s_facts:
        kind: Pod
        namespace: example-tower
        label_selectors:
          - app=tower
      register: tower_pods

    - name: Verify there are two tower pods
      assert:
        that: '{{ (tower_pods.resources | length) == 2 }}'

- name: Verify tower functionality
  hosts: k8s

  vars: []

  tasks: []
